#!/usr/bin/env bash
# Usage: box ansible
# Summary: install ansible
# Help:
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

action "install ansible from source"
  git clone git://github.com/ansible/ansible.git --recursive
  cd ./ansible
  source ./hacking/env-setup
  # Once running the env-setup script you’ll be running from checkout and the
  # default inventory file will be /etc/ansible/hosts. You can optionally specify
  # an inventory file (see Inventory) other than /etc/ansible/hosts:
  echo "127.0.0.1" > ~/ansible_hosts
  export ANSIBLE_INVENTORY=~/ansible_hosts
ok

action "install python dependencies"
  # python should already be installed
  #
  if [ "$NS_PLATFORM" == "darwin" ]; then
    pip install paramiko PyYAML Jinja2 httplib2 six
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
    sudo pip install paramiko PyYAML Jinja2 httplib2 six
  fi
ok

# # Note when updating ansible, be sure to not only update the source tree,
# # but also the “submodules” in git which point at Ansible’s own modules (not the same kind of modules, alas).
# $ git pull --rebase
# $ git submodule update --init --recursive

exit
