#!/usr/bin/env bash
# Usage: box redis
# Summary: write a summary for your new command
# Help: This will print out when you run box help redis
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/bash_functions.sh"
set -e

bot "BOXBOT!"
get_platform

bot "Redis"

if [ "$NS_PLATFORM" == "darwin" ]; then
	require_brew redis

	# To have launchd start redis at login:
	ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
	# Then to load redis now:
	launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
  
  # a gui client for redis
  require_cask rdm
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	sudo apt-add-repository ppa:chris-lea/redis-server
	sudo apt-get update
	sudo apt-get install redis-server
	# does it auto start ?
fi
