#!/usr/bin/env bash
# Usage: box heroku-toolbelt
# Summary: install heroku toolbelt
# Help:
#
source "$_BOX_ROOT/lib/box_functions"
set -e

bot "BOXBOT!"
get_platform

bot "Heroku Tools"

if [ "$NS_PLATFORM" == "darwin" ]; then
	require_cask heroku-toolbelt
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
fi
