#!/usr/bin/env bash
# Usage: box php
# Summary: install php Development tools
# Help: This will print out when you run box help php
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Installing PHP 5.6 Development tools"

if [ "$NS_PLATFORM" == "darwin" ]; then
  brew tap homebrew/dupes
  brew tap homebrew/versions
  brew tap homebrew/homebrew-php
  brew options php56
  require_brew php56
  brew link --overwrite php56
  ln -sfv /usr/local/opt/php56/*.plist ~/Library/LaunchAgents
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.php56.plist

  # edit /etc/apache2/httpd.conf
  # LoadModule php5_module /usr/local/Cellar/php56/5.6.3/libexec/apache2/libphp5.so
fi

if [ "$NS_PLATFORM" == "linux" ]; then
  die "not yet implemented"
fi

exit
