#!/usr/bin/env bash
# Usage: box new
# Summary: create a new command for box
# Help: This will print out when you run `box help new`.
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Creating New Box Command"

if [[ $# -eq 0 ]] ; then
  error 'please provide a name for your new command'
  die
fi

command_file="$HOME/.box/libexec/box-$1"
if [ -s "$command_file" ]
  then
    die "COMMAND EXISTS"
  else
    action "create $command_file"
    touch $command_file
    chmod a+x $command_file
    echo "$TEMPLATE" > $command_file
    ok
fi

exit
