#!/usr/bin/env bash
# Usage: box sqlite
# Summary: install sqlite and a GUI browser for sqlite
# Help:
#
source "$_BOX_ROOT/lib/box_functions"
set -e

bot "BOXBOT!"
get_platform

bot "Sqlite"

if [ "$NS_PLATFORM" == "darwin" ]; then
	require_brew sqlite

  # sqlite ui browser
  require_cask sqlitebrowser
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	sudo apt-get install -y sqlite
fi
