#!/usr/bin/env bash
# Usage: box drobosync
# Summary: rsync data between external drives
# Help:
#
source "$_BOX_ROOT/lib/box_functions"

action 'Kick off a Time Machine Backup'
tmutil startbackup -a

action 'sync OTG128x01 to Drobo'
rsync -avzh /Volumes/OTG128x01/ /Volumes/Drobo/Archive/OTG128x01/

action 'sync Drobo with SeagateBackup'
rsync -avzh /Volumes/Drobo/Archive/ /Volumes/SeagateBackup/Drobo/

action 'sync Drobo with Elements2TB'
rsync -avzh /Volumes/Drobo/Archive/ /Volumes/Elements2TB/Drobo/
