#!/usr/bin/env bash
# Usage: box xcode
# Summary: install xcode developer tools 
# Help:
#
source "$_BOX_ROOT/lib/box_functions"
set -e

bot "BOXBOT!"
get_platform

bot "Xcode"

if [ "$NS_PLATFORM" == "darwin" ]; then
  bot "Checking Dependencies"

	running "checking Xcode Command Line Tools install"
  if [[ $(xcode-select -p) != "/Applications/Xcode.app/Contents/Developer" ]]; then
	  action "  installing"
	  xcode-select --install
	fi
  ok
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	die 'xcode not available for linux'
fi
