#!/usr/bin/env bash
# Usage: box android
# Summary: install android Development environment
# Help:
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Install Android Development tools"

if [ "$NS_PLATFORM" == "darwin" ]; then
  $_BOX_ROOT/bin/box java

  action "Install Android Tools"
  brew install android-platform-tools
  ok

  action "Install Android Studio"
	require_cask android-studio
	ok

	# action "Install APK Tool"
	# require_brew apktool
	# ok

fi

if [ "$NS_PLATFORM" == "linux" ]; then
	$_BOX_ROOT/bin/box java

  action "Install Android Tools"
  sudo apt-get install -y android-tools-adb android-tools-fastboot
  ok

	action "Install Android Studio"
	sudo apt-add-repository ppa:paolorotolo/android-studio
	sudo apt-get update
	sudo apt-get install -y android-studio

fi

exit
