#!/usr/bin/env bash
# Usage: box virtualbox
# Summary: install virtualbox and vagrant tools
# Help:
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Installing Virtualbox & Vagrant"

running "Installing Virtualbox and Vagrant"
if [ "$NS_PLATFORM" == "darwin" ]; then
  require_cask virtualbox
  require_cask vagrant
fi
if [ "$NS_PLATFORM" == "linux" ]; then
  sudo apt-get install -y virtualbox
  sudo apt-get install -y vagrant
fi
ok

exit
