#!/usr/bin/env bash
# Usage: box sizeup
# Summary: install sizeup (a linux style window manager for OSX)
# Help:
#
source "$_BOX_ROOT/lib/box_functions"
set -e

bot "BOXBOT!"
get_platform

bot "Sizeup Window Manager"

if [ "$NS_PLATFORM" == "darwin" ]; then
  # http://www.irradiatedsoftware.com/sizeup/
  require_cask sizeup

  running "Start SizeUp at login"
  defaults write com.irradiatedsoftware.SizeUp StartAtLogin -bool true;ok

  running "Don't show the preferences window on next start"
  defaults write com.irradiatedsoftware.SizeUp ShowPrefsOnNextStart -bool false;ok
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	die 'depending on your linux you already have a nice window manager..'
fi
