#!/usr/bin/env bash
# Usage: box geektool
# Summary: install geektool and started scripts
# Help: 
#
source "$_BOX_ROOT/lib/box_functions"
set -e

bot "BOXBOT!"
get_platform

bot "Geektool"

if [ "$NS_PLATFORM" == "darwin" ]; then
  require_cask geektool

  $_BOX_ROOT/lib/box-geektool/install.sh
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	die 'geektool not available fo linux'
fi
