#!/usr/bin/env bash
# Usage: box php
# Summary: install php Development tools
# Help: This will print out when you run box help php
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Installing PHP 7.0.1 Development tools"

if [ "$NS_PLATFORM" == "darwin" ]; then
  brew tap homebrew/dupes
  brew tap homebrew/versions
  brew tap homebrew/homebrew-php
  brew options php70
  require_brew php70
  brew link --overwrite php70
  ln -sfv /usr/local/opt/php70/*.plist ~/Library/LaunchAgents
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.php70.plist

  # edit /etc/apache2/httpd.conf
  # LoadModule php7_module /usr/local/Cellar/php70/7.0.1/libexec/apache2/libphp7.so
fi

if [ "$NS_PLATFORM" == "linux" ]; then
  die "not yet implemented"
fi

exit
