#!/usr/bin/env bash
# Usage: box add-droid
# Summary: add the .droid repo
# Help:
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

running "fetching the .droid repo"
git clone https://github.com/bhedana/.droid $HOME/.droid
ok

running "adding .droid to path"
profile_write 'eval "$($HOME/.droid/bin/droid init -)"' $CODERONIN_DOTFILE
ok

exit
