#!/usr/bin/env bash
# Usage: box scapy
# Summary: write a summary for your new command
# Help: This will print out when you run box help scapy
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/box_functions"
set -e

bot "BOXBOT!"
get_platform

bot "Scapy"

# check that python is installed -- warn and exit if not found
command -v python >/dev/null 2>&1 || { 
  echo >&2 "Scapy requires python but it does not appear to be installed.  Aborting."; exit 1; 
}

if [ "$NS_PLATFORM" == "darwin" ]; then
  action "Install libdnet and its Python wrapper"
  wget http://libdnet.googlecode.com/files/libdnet-1.12.tgz
  tar xfz libdnet-1.12.tgz &>/dev/null
  cd libdnet-1.12
  ./configure &>/dev/null
  make &>/dev/null
  sudo make install &>/dev/null
  cd python
  python setup.py install &>/dev/null
  cd ../../
  sudo rm -rf libdnet-1.12*
  ok
  
  action "Install libpcap and its Python wrapper"
  wget http://dfn.dl.sourceforge.net/sourceforge/pylibpcap/pylibpcap-0.6.2.tar.gz 
  tar xfz pylibpcap-0.6.2.tar.gz &>/dev/null
  cd pylibpcap-0.6.2
  sudo python setup.py install &>/dev/null
  cd ../
  sudo rm -rf pylibpcap-0.6.2*
  ok
  
  # Optionally: Install readline:
  # python `python -c "import pimp; print pimp.__file__"` -i readline
fi

action "install scapy"
wget scapy.net 
mv index.html scapy-latest.zip
unzip scapy-latest.zip &>/dev/null
rm scapy-latest.zip

cd scapy-2.*
sudo python setup.py install &>/dev/null
cd ..
sudo rm -rf scapy-2*
ok
