#!/usr/bin/env bash
# Usage: box mysql
# Summary: write a summary for your new command
# Help: This will print out when you run box help mysql
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/bash_functions.sh"
set -e

bot "MySQL"

if [ "$NS_PLATFORM" == "darwin" ]; then
	require_brew mysql

	# launch mysql at startup
	ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents
	# launch mysql now
	launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist

	# install ui query browser
	require_cask sequel-pro
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	sudo apt-get install mysql-server
	sudo mysql_install_db
	sudo /usr/bin/mysql_secure_installation
  
  # if i were on debian which ui would i want?
  # phpmyadmin ?
  # MySql Workbench ?
fi
