#!/usr/bin/env bash
# Usage: box sublime-text
# Summary: write a summary for your new command
# Help: This will print out when you run box help sublime-text
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/bash_functions.sh"
# set -e

bot "BOXBOT!"
get_platform

echo "Which Editor would you like"
echo " 1. Atom"
echo " 2. Sublime"
echo "Select then press enter"
read editor

if [ $editor = '1' ] ; then
  $_BOX_ROOT/lib/box-text-editor/atom.sh
fi

if [ $editor = '2' ] ; then
  $_BOX_ROOT/lib/box-text-editor/sublime.sh
fi

die
