#!/usr/bin/env bash
# Usage: box docker
# Summary: install docker tools
# Help:
#
source "$_BOX_ROOT/lib/box_functions"
set -e

bot "BOXBOT!"
get_platform

bot "Docker"

if [ "$NS_PLATFORM" == "darwin" ]; then
  require_brew boot2docker
  boot2docker init
  boot2docker start
  $(boot2docker shellinit)
  require_brew docker-compose
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	die 'not implemented'
fi
