#!/usr/bin/env bash
# Usage: box nodejs
# Summary: install nodejs Development tools
# Help: This will print out when you run box help nodejs
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Installing NodeJS Development tools"

if [ "$NS_PLATFORM" == "darwin" ]; then
fi

if [ "$NS_PLATFORM" == "linux" ]; then
fi

# node version manager
# allows per directory node versions with .nvmrc files
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash

# nvm load in coderonin file
profile_write 'export NVM_DIR="$HOME/.nvm"' $CODERONIN_DOTFILE
profile_write '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' $CODERONIN_DOTFILE

# immediately load nvm so we can install node and npm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

nvm install 5.4
nvm alias default 5.4

npm install -g sails
npm install -g bower


# ###############################################################################
# bot "NPM Globals..."
# ###############################################################################
# require_npm antic
# # http://ionicframework.com/
# require_npm cordova
# require_npm ionic
# # https://github.com/markdalgleish/bespoke.js
# require_npm generator-bespoke
# require_npm grunt
# require_npm gulp
# require_npm jshint
# # http://devo.ps/blog/goodbye-node-forever-hello-pm2/
# require_npm pm2
# require_npm prettyjson
# require_npm supervisor
# # https://github.com/sindresorhus/trash
# require_npm trash
# # https://github.com/MrRio/vtop
# require_npm vtop
# require_npm yo

# Creating your Sails app
# You will want to navigate to the directory in which you would like your app to be located, e.g. /var/www and then run:
#
# sails new project-name
# This will add the required files to your project, and create a directory named project-name.
#
# cd project-name
# npm install
# sails lift

exit
