#!/usr/bin/env bash
# Usage: box scala
# Summary: install scala Development tools
# Help: 
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Installing Scala Development tools"

if [ "$NS_PLATFORM" == "darwin" ]; then
	# install JDK
	java -version

	require_brew scala
	# install scala build tool
	require_brew sbt

	# optional
	echo 'SBT_OPTS="-XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M -Xmx2G"' >> ~/.sbtconfig

	# eclipse scala-ide
	require_cask 'scala-ide'
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	# install JDK
	sudo apt-get install -y openjdk-7-jdk

	# install scala
	sudo apt-get install -y scala

	# install scala build tool
	# install scala build tool
	echo "deb http://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
	sudo apt-get update
	sudo apt-get install -y sbt

	# download and install eclipse scala-ide
	# http://scala-ide.org/
fi

exit
