#!/usr/bin/env bash
# Usage: box sqlite
# Summary: write a summary for your new command
# Help: This will print out when you run box help sqlite
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/box_functions"
set -e

bot "BOXBOT!"
get_platform

bot "Sqlite"

if [ "$NS_PLATFORM" == "darwin" ]; then
	require_brew sqlite
	
  # sqlite ui browser
  require_cask sqlitebrowser
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	sudo apt-get install -y sqlite
fi
