#!/usr/bin/env bash
# Usage: box java
# Summary: install jenv, java, and eclipse-ide
# Help:
#
set -e

bot "BOXBOT!"
get_platform

bot "Java Development Tools"

if [ "$NS_PLATFORM" == "darwin" ]; then
  # jEnv is a command line tool to help you forget how to set the JAVA_HOME environment variable
  action "Install Java Version Manager"
  brew tap jenv/jenv
  require_brew jenv

  coderonin_write 'export PATH="$HOME/.jenv/bin:$PATH"'
  coderonin_write 'if which jenv > /dev/null; then eval "$(jenv init -)"; fi'
  ok

  action "install Java"
  require_cask java
  ok
fi

if [ "$NS_PLATFORM" == "linux" ]; then
  action "Install Java Version Manager"
  git clone https://github.com/gcuisinier/jenv.git ~/.jenv

  coderonin_write 'export PATH="$HOME/.jenv/bin:$PATH"'
  coderonin_write 'if which jenv > /dev/null; then eval "$(jenv init -)"; fi'

  action "install oracle java jdk"
  sudo apt-get purge openjdk*
  sudo add-apt-repository ppa:webupd8team/java
  sudo apt-get update
  sudo apt-get install -y oracle-java8-installer
  sudo apt-get install -y oracle-java8-set-default
  ok
fi

action "restarting shell"
exec $SHELL -l
ok

exit