#!/usr/bin/env bash
# Usage: box java
# Summary: install jenv for java version management
# Help:
#  jenv help.. see http://www.jenv.be
#
source "$_BOX_ROOT/lib/box_functions"
# set -e

bot "BOXBOT!"
get_platform

bot "Java Development Tools"

if [ "$NS_PLATFORM" == "darwin" ]; then
  # jEnv is a command line tool to help you forget how to set the JAVA_HOME environment variable
  action "Install Java Version Manager"
  brew tap jenv/jenv
  require_brew jenv

  profile_write 'export PATH="$HOME/.jenv/bin:$PATH"' $CODERONIN_DOTFILE
  profile_write 'if which jenv > /dev/null; then eval "$(jenv init -)"; fi' $CODERONIN_DOTFILE
  ok

  action "install Java"
  require_cask java
  ok
fi

if [ "$NS_PLATFORM" == "linux" ]; then
  action "Install Java Version Manager"
  git clone https://github.com/gcuisinier/jenv.git ~/.jenv

  profile_write 'export PATH="$HOME/.jenv/bin:$PATH"' $CODERONIN_DOTFILE
  profile_write 'if which jenv > /dev/null; then eval "$(jenv init -)"; fi' $CODERONIN_DOTFILE

  action "install oracle java jdk"
  sudo apt-get purge openjdk*
  sudo add-apt-repository ppa:webupd8team/java
  sudo apt-get update
  sudo apt-get install -y oracle-java8-installer
  sudo apt-get install -y oracle-java8-set-default
  ok
fi

action "restarting shell"
exec $SHELL -l
ok

action "emabling jenv plugins"
jenv enable-plugin maven ant
jenv enable-plugin maven golo
jenv enable-plugin maven gradle
jenv enable-plugin maven grails
jenv enable-plugin maven groovy
jenv enable-plugin maven lein
jenv enable-plugin maven maven
jenv enable-plugin maven sbt
jenv enable-plugin maven scala
jenv enable-plugin maven vlt

if [ "$NS_PLATFORM" == "darwin" ]; then
# action "finding current java versions"
# read /Library/Java/JavaVirtualMachines/
# for each entry
# jenv add /Library/Java/JavaVirtualMachines/{entry}/Contents/Home
fi

if [ "$NS_PLATFORM" == "linux" ]; then

fi

exit

# Configure JVM in jenv
# $ jenv add /path/to/java/home

# Configure which JVM to use (globally, by directory or for the current shell instance)
# $ jenv (global|local|shell) oracle-1.7.0

# Check that works
# $ java -version

# Add JVM Options (globally, by directory or for the current shell instance)
# $ jenv global|local|shell)-options "-Xmx512m"

# Check that works
# $ jenv info java

# Sets a local application-specific Java version by writing the version name to
# a .java-version file in the current directory.
# This version overrides the global version, and can be overridden itself by
# setting the JENV_VERSION environment variable or with the jenv shell command.
# $ jenv local oracle-1.7
