#!/usr/bin/env bash
# Usage: box hackrf
# Summary: install hackrf tools
# Help: 
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Installing HackRF Tools"

if [ "$NS_PLATFORM" == "darwin" ]; then
  action "Install python preqequisites"
  require_brew python
  require_brew gcc
  require_brew swig
  ok
  
  action "Install prerequisite python packages"
  pip install numpy
  pip install Cheetah
  pip install lxml
  pip install scipy
  export PKG_CONFIG_PATH="/usr/X11/lib/pkgconfig"
  pip install matplotlib
  # Install wxmac 2.9 with python bindings
  require_brew wxmac --python
  ok

  brew tap godber/godber

  action "Install gnuradio"
  require_brew gnuradio
  ok

  mkdir $HOME/.gnuradio
  profile_write '[grc]' $HOME/.gnuradio/config.conf
  profile_write 'local_blocks_path=/usr/local/share/gnuradio/grc/blocks' $HOME/.gnuradio/config.conf

  action "Install HackRF & RTL-SDR related blocks"
  require_brew rtl-sdr
  require_brew hackrf
  require_brew gr-osmosdr
  ok
  
  action "Install GQRX"
  require_brew gqrx
  brew linkapps gqrx
  ok

  action "Installing Inspectrum"
  brew install qt5 fftw cmake pkg-config
  git clone https://github.com/miek/inspectrum.git
  cd inspectrum
  mkdir build
  cd build
  CMAKE_PREFIX_PATH=$(brew --prefix qt5)/lib/cmake cmake ..
  make install

  # this process allows all software to install without complaint
  # however, the gr-osmosdr install causes gnuradio-companion to fail to start
  # Fatal Python error: PyThreadState_Get: no current thread
  # 
fi

if [ "$NS_PLATFORM" == "linux" ]; then
  action "Installing GNURadio"
  mkdir ~/hackrf_files
  wget http://www.sbrac.org/files/build-gnuradio -O ~/hackrf_files/build-gnuradio.sh
  chmod 744 ~/hackrf_files/build-gnuradio.sh
  ~/hackrf_files/build-gnuradio.sh
  ok
  
  action "Installing HackRF tools"
  cd ~/hackrf_files && git clone https://github.com/mossmann/hackrf.git
  cd ~/hackrf_files/hackrf/host && mkdir build && cd build && cmake .. && make && sudo make install && sudo ldconfig
  ok
  
  action "Installing Inspectrum"
  sudo apt-get install qt5-default libfftw3-dev cmake pkg-config
  git clone https://github.com/miek/inspectrum.git
  cd inspectrum
  mkdir build
  cd build
  cmake ..
  make
  sudo make install
  ok
  
fi

exit
