#!/usr/bin/env bash
# Usage: box memcached
# Summary: install memcached
# Help: 
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Installing MemcacheD"

if [ "$NS_PLATFORM" == "darwin" ]; then
  require_brew memcached
  
  running "setting memcached to start automatically"
  # To have launchd start memcached at login:
  ln -sfv /usr/local/opt/memcached/*.plist ~/Library/LaunchAgents
  # Then to load memcached now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.memcached.plist
  ok
  
  running "installing memcache-top"
  require_brew memcache-top
  ok
fi

if [ "$NS_PLATFORM" == "linux" ]; then
  running "installing memcached"
  sudo apt-get install memcached
  ok

  running "setting memcached to start automatically"
  sudo update-rc.d memcached defaults
  sudo service memcached start
  ok

  # To verify if Memcached is install and functioning, run the commands below to view its stats.
  # echo "stats settings" | nc localhost 11211
  # watch "echo stats | nc 127.0.0.1 11211"
fi

exit
