#!/usr/bin/env bash
# Usage: box essentials
# Summary: install essential tools
# Help: Customize in `~/.laptop.local`
# ------------------------------
#   Your `~/.laptop.local` is run at the end of the Essentials command.
#   Put desired customizations there.
#   See .laptop.local.example for example usage
#
source "$_BOX_ROOT/lib/box_functions"
set -e

bot "BOXBOT!"
get_platform

bot "System Essentials"

# add line to .profile to source our CODERONIN_DOTFILE
profile_write "source $CODERONIN_DOTFILE" "$HOME/.profile"
# add line to .bash_profile to source our CODERONIN_DOTFILE
profile_write "source $CODERONIN_DOTFILE" "$HOME/.bash_profile"
# add line to .zshrc to source our CODERONIN_DOTFILE
profile_write "source $CODERONIN_DOTFILE" "$HOME/.zshrc"

if [ "$NS_PLATFORM" == "darwin" ]; then
  source "$_BOX_ROOT/lib/box-essentials/_darwin.sh"
fi

if [ "$NS_PLATFORM" == "linux" ]; then
  source "$_BOX_ROOT/lib/box-essentials/_linux.sh"
fi
