#!/usr/bin/env bash
# Usage: box nodejs
# Summary: install nodejs Development tools
# Help: This will print out when you run box help nodejs
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Installing NodeJS Development tools"

# node version manager
# allows per directory node versions with .nvmrc files
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash

# nvm load in coderonin file
profile_write 'export NVM_DIR="$HOME/.nvm"' $CODERONIN_DOTFILE
profile_write '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' $CODERONIN_DOTFILE

# immediately load nvm so we can install node and npm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

nvm install 5.4
nvm alias default 5.4

###############################################################################
bot "NPM Installing ESLint and plugins as globals..."
###############################################################################
npm install -g eslint
npm install -g eslint-plugin-arrow-function
npm install -g eslint-plugin-babel
npm install -g eslint-plugin-chai
npm install -g eslint-plugin-filenames
npm install -g eslint-plugin-html
npm install -g eslint-plugin-json
npm install -g eslint-plugin-jsdoc
npm install -g eslint-plugin-lodash3
npm install -g eslint-plugin-member-order
npm install -g eslint-plugin-mocha
npm install -g eslint-plugin-node
npm install -g eslint-plugin-objects
npm install -g eslint-plugin-react
npm install -g eslint-plugin-smells

exit
