#!/usr/bin/env bash
# Usage: box python
# Summary: write a summary for your new command
# Help: This will print out when you run box help python
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/bash_functions.sh"
# set -e

bot "Python"
get_platform

if [ "$NS_PLATFORM" == "darwin" ]; then
  action "Install pyenv"
  require_brew pyenv

  action "add pyenv init"
  coderonin_write 'eval "$(pyenv init -)"'

  action "check out virtualenv plugin"
  require_brew pyenv-virtualenv

  action "add virtualenv init"
  coderonin_write 'eval "$(pyenv virtualenv-init -)"'

  pyenv install 2.7.11
  pyenv install 3.5.1
  pyenv rehash

	# try pycharm IDE
  require_cask pycharm-ce

  # # list virtualenvs
  # pyenv virtualenvs

  # # create a new virtualenv
  # pyenv virtualenv $ENV_NAME

  # # destroy a  virtualenv
  # pyenv uninstall $ENV_NAME

  # # create a directory switch for a virtualenv
  # python local $ENV_NAME
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	# Databases: You may not need all of these;
	# none are explicit dependencies of other items in this script.
	# SQLite and MySQL are pretty generally used for web development
	sudo apt-get install -y python-mysqldb libmysqlclient-dev
	sudo apt-get install -y libxml2-dev libxslt-dev  # needed for Python package 'lxml'
	
	sudo apt-get install -y python python-setuptools python-dev
	sudo easy_install -U pip

	# virtualenv, virtualenvwrapper stuff
	sudo pip install virtualenv virtualenvwrapper
	
	# install oracle java jdk
	sudo apt-get purge openjdk*
	sudo add-apt-repository ppa:webupd8team/java
	sudo apt-get update
	sudo apt-get install -y oracle-java8-installer
	sudo apt-get install -y oracle-java8-set-default

	# install pycharm
	wget -q -O - http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
	sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu $(lsb_release -sc)-getdeb apps" >> /etc/apt/sources.list.d/getdeb.list'
	sudo apt-get update
	sudo apt-get install -y pycharm
fi

