#!/usr/bin/env bash
# Usage: box mysql
# Summary: install mysql and a gui for mysql
# Help:
#
source "$_BOX_ROOT/lib/box_functions"
set -e

bot "MySQL"

if [ "$NS_PLATFORM" == "darwin" ]; then
	require_brew mysql

	# launch mysql at startup
	ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents
	# launch mysql now
	launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist

	# install ui query browser
	require_cask sequel-pro
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	sudo apt-get install -y mysql-server
	sudo mysql_install_db
	sudo /usr/bin/mysql_secure_installation

  # if i were on debian which ui would i want?
  # phpmyadmin ?
  # MySql Workbench ?
fi
