#!/usr/bin/env bash
# Usage: box essentials
# Summary: install essential tools
# Help: Customize in `~/.laptop.local`
# ------------------------------
#   Your `~/.laptop.local` is run at the end of the Essentials command.
#   Put desired customizations there.
#   See .laptop.local.example for example usage
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Install System Essential tools"

# ensure our primary customizations dotfile is present
profile_write 'eval "$($HOME/.box/bin/box init -)"' $CODERONIN_DOTFILE

# add line to .profile to source our CODERONIN_DOTFILE
profile_write "source $CODERONIN_DOTFILE" "$HOME/.profile"
# add line to .bash_profile to source our CODERONIN_DOTFILE
profile_write "source $CODERONIN_DOTFILE" "$HOME/.bash_profile"
# add line to .zshrc to source our CODERONIN_DOTFILE
profile_write "source $CODERONIN_DOTFILE" "$HOME/.zshrc"

if [ "$NS_PLATFORM" == "darwin" ]; then
  action "Checking Dependencies"
  running "checking Xcode Command Line Tools install"
  if [[ $(xcode-select -p) != "/Applications/Xcode.app/Contents/Developer" ]]; then
    action "  installing"
    xcode-select --install
  fi
  ok
fi

source "$_BOX_ROOT/lib/box-essentials/_$NS_PLATFORM.sh"

exit
