#!/usr/bin/env bash
# Usage: box cligoodness
# Summary: write a summary for your new command
# Help: This will print out when you run box help cligoodness
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/bash_functions.sh"
set -e

bot "BOXBOT!"
get_platform

bot "CLI-goodness"

# cli-goodness is an old repo of personal tools that will go away once i finish migrating all those chef repos and truecrypt containers to some other encrypted storage mechanism
git_clone_or_update https://github.com/bhedana/cli-goodness.git ~/.cli-goodness

coderonin_write "export CLI_GOODNESS=$HOME/.cli-goodness"
coderonin_write "source $CLI_GOODNESS/dotfile.sh"