#!/usr/bin/env bash
# Usage: box defaults
# Summary: configure machine with sensable default configuration
# Help:
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Setting System Defaults"

source "$_BOX_ROOT/lib/box-defaults/_$NS_PLATFORM.sh"
ln -s $_BOX_ROOT/lib/box-defaults/_aliases_$NS_PLATFORM $HOME/.aliases

profile_write "source $HOME/.aliases" $CODERONIN_DOTFILE

exit
