#!/usr/bin/env bash
# Usage: box python
# Summary: install python Development tools
# Help:
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Installing Python Development tools"

if [ "$NS_PLATFORM" == "darwin" ]; then
  action "Install pyenv"
  require_brew pyenv

  action "add pyenv init"
  profile_write 'eval "$(pyenv init -)"' $CODERONIN_DOTFILE

  action "check out virtualenv plugin"
  require_brew pyenv-virtualenv

  action "add virtualenv init"
  profile_write 'eval "$(pyenv virtualenv-init -)"' $CODERONIN_DOTFILE

	# try pycharm IDE
  require_cask pycharm-ce
fi

if [ "$NS_PLATFORM" == "linux" ]; then
  # Databases: You may not need all of these;
  # none are explicit dependencies of other items in this script.
  # SQLite and MySQL are pretty generally used for web Development
  sudo apt-get install -y python-mysqldb libmysqlclient-dev
  sudo apt-get install -y libxml2-dev libxslt-dev  # needed for Python package 'lxml'

  sudo apt-get install -y python python-setuptools python-dev
  sudo easy_install -U pip

  action "Install pyenv"
  git_clone_or_update https://github.com/yyuu/pyenv.git ~/.pyenv

  action "add pyenv init"
  profile_write 'export PYENV_ROOT="$HOME/.pyenv"' $CODERONIN_DOTFILE
  profile_write 'export PATH="$PYENV_ROOT/bin:$PATH"' $CODERONIN_DOTFILE
  profile_write 'eval "$(pyenv init -)"' $CODERONIN_DOTFILE

  action "check out virtualenv plugin"
  git_clone_or_update https://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv

  action "add virtualenv init"
  profile_write 'eval "$(pyenv virtualenv-init -)"' $CODERONIN_DOTFILE

  $_BOX_ROOT/bin/box java

  action "install pycharm-ce"
  wget -q -O - http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
  sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu $(lsb_release -sc)-getdeb apps" >> /etc/apt/sources.list.d/getdeb.list'
  sudo apt-get update
  sudo apt-get install -y pycharm
fi

exit
