#!/usr/bin/env bash
# Usage: box sublime-text
# Summary: install a good text editor
# Help:
#
source "$_BOX_ROOT/lib/box_functions"
# set -e

bot "BOXBOT!"
get_platform

echo "Which Editor would you like"
echo " 1. Atom"
echo " 2. Sublime"
echo "Select then press enter"
read editor

if [ $editor = '1' ] ; then
  $_BOX_ROOT/lib/box-text-editor/atom.sh
fi

if [ $editor = '2' ] ; then
  $_BOX_ROOT/lib/box-text-editor/sublime.sh
fi

exit
