#!/usr/bin/env bash
# Usage: box geektool
# Summary: install geektool and started scripts
# Help: 
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Installing Geektool"

if [ "$NS_PLATFORM" == "darwin" ]; then
  require_cask geektool
  $_BOX_ROOT/lib/box-geektool/install.sh
fi

if [ "$NS_PLATFORM" == "linux" ]; then
  running "install conky"
  sudo apt-get install conky curl lm-sensors hddtemp
  ok

  running "copying config"
  cp $_BOX_ROOT/lib/box-conky/_conkyrc ~/.conkyrc
  ok

  action "adding conky to autostart"
  cp $_BOX_ROOT/lib/box-conky/conky.desktop ~/.config/autostart
  ok
fi

exit
