#!/usr/bin/env bash
# Usage: box docker
# Summary: install docker tools
# Help:
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Install Docker"

if [ "$NS_PLATFORM" == "darwin" ]; then

  # Running Docker on Mac requires VirtualBox so if you don’t have it already:
  require_cask virtualbox

  # Then install Docker and the helper tool boot2docker:
  require_brew docker
  require_brew boot2docker

  # boot2docker takes care of the VM that Docker runs in. To get things started
  # it needs to download the Docker VM and start a daemon that the docker command
  # line tool will talk to:
  running "boot2docker initialize"
    boot2docker init
    boot2docker start
    $(boot2docker shellinit)
  ok

  running "boot2docker shellinit"
    touch "$CODERONIN_DOTFILE"
    profile_write 'eval "$(boot2docker shellinit)"' $CODERONIN_DOTFILE
  ok

  # require_brew docker-compose
fi

if [ "$NS_PLATFORM" == "linux" ]; then
  # update apt and ensure
  apt-get install apt-transport-https ca-certificates
  sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

  profile_write 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' /etc/apt/sources.list.d/docker.list

  # Update the APT package index.
  apt-get update
  # Purge the old repo if it exists.
  apt-get purge lxc-docker
  # Verify that APT is pulling from the right repository.
  apt-cache policy docker-engine

  # For Ubuntu Trusty, Vivid, and Wily, it’s recommended to install the linux-image-extra kernel package.
  # The linux-image-extra package allows you use the aufs storage driver.
  sudo apt-get install linux-image-extra-$(uname -r)

  # If you are installing on Ubuntu 14.04 or 12.04, apparmor is required.
  apt-get install apparmor

  # Install Docker.
  sudo apt-get install docker-engine
  # Start the docker daemon.
  sudo service docker start
  # Verify docker is installed correctly.
  sudo docker run hello-world
fi

exit
