#!/usr/bin/env bash
# Usage: box hackrf
# Summary: install hackrf tools
# Help: This will print out when you run box help hackrf
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Installing HackRF Tools"

if [ "$NS_PLATFORM" == "darwin" ]; then
  action "Install python preqequisites"
  require_brew python
  require_brew gcc
  require_brew swig
  ok
  
  action "Install prerequisite python packages"
  pip install numpy
  pip install Cheetah
  pip install lxml
  # pip install https://github.com/scipy/scipy/archive/v0.12.0.tar.gz
  pip install scipy
  export PKG_CONFIG_PATH="/usr/X11/lib/pkgconfig"
  # pip install https://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.2.1/matplotlib-1.2.1.tar.gz
  pip install matplotlib
  # Install wxmac 2.9 with python bindings
  require_brew wxmac --python
  ok

  # brew tap andresv/homebrew-gnuradio
  brew tap godber/godber

  action "Install gnuradio"
  require_brew gnuradio
  ok

  action "Install rtl-sdr"
  require_brew rtl-sdr
  ok

  action "Install hackrf"
  require_brew hackrf
  ok

  mkdir ~/.gnuradio
  profile_write '[grc]' '~/.gnuradio/config.conf'
  profile_write 'local_blocks_path=/usr/local/share/gnuradio/grc/blocks' '~/.gnuradio/config.conf'

  action "Install HackRF & RTL-SDR related blocks"
  require_brew gnuradio-osmosdr
  ok
  
  action "Install GQRX"
  require_brew gqrx
  brew linkapps gqrx
  ok

  # gqrx
  # And then configure it to use the HackRF. 
  # Probably best to start the sample rate at 1000000 until you know how much your system can handle.
  #
  # Congratulations!!
  # Everything should now be working. It is time to give it a try! Below are some of the programs you can try
  #
  # gnuradio-companion
  # osmocom_fft -a hackrf

fi

if [ "$NS_PLATFORM" == "linux" ]; then
  action "Installing GNURadio"
  mkdir ~/hackrf_files
  wget http://www.sbrac.org/files/build-gnuradio -O ~/hackrf_files/build-gnuradio.sh
  chmod 744 ~/hackrf_files/build-gnuradio.sh
  ~/hackrf_files/build-gnuradio.sh
  ok
  
  action "Installing HackRF tools"
  cd ~/hackrf_files && git clone https://github.com/mossmann/hackrf.git
  cd ~/hackrf_files/hackrf/host && mkdir build && cd build && cmake .. && make && sudo make install && sudo ldconfig
  ok
fi

exit
