#!/usr/bin/env bash
# Usage: box defaults
# Summary: configure machine with sensable default configuration
# Help:
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Setting System Defaults"

if [ "$NS_PLATFORM" == "darwin" ]; then
  source "$_BOX_ROOT/lib/box-defaults/_darwin.sh"
  ln -s $_BOX_ROOT/lib/box-defaults/_aliases_darwin $HOME/.aliases
fi

if [ "$NS_PLATFORM" == "linux" ]; then
  source "$_BOX_ROOT/lib/box-defaults/_linux.sh"
  ln -s $_BOX_ROOT/lib/box-defaults/_aliases_linux $HOME/.aliases
fi

profile_write "source $HOME/.aliases" $CODERONIN_DOTFILE

exit
