#!/usr/bin/env bash
# Usage: box new
# Summary: scaffold a new command for box
# Help: This will print out when you run `box help new`.
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/bash_functions.sh"
set -e

command_file="$HOME/.box/libexec/box-$1"

bot "BOXBOT!"
get_platform

bot "New Box Command"

if [ -s "$command_file" ]
  then 
    die "COMMAND EXISTS"
  else
    action "create $command_file"
    touch $command_file
    chmod a+x $command_file
    cat >$command_file <<EOL
#!/usr/bin/env bash
# Usage: box $1
# Summary: write a summary for your new command
# Help: This will print out when you run box help $1
# You can have multiple lines even!
#
#    Show off an example indented
#
source "\$_BOX_ROOT/lib/bash_functions.sh"
set -e

EOL
    ok
fi

