#!/usr/bin/env bash
# Usage: box postgres
# Summary: install postgres and pgadmin3
# Help: This will print out when you run box help postgres
# You can have multiple lines even!
#
#    Show off an example indented
#
source "$_BOX_ROOT/lib/box_functions"

banner

get_platform

bot "Installing Postgres"

if [ "$NS_PLATFORM" == "darwin" ]; then
	require_brew postgresql

	# launch postgres at startup
	ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
	# initialize database
	initdb /usr/local/var/postgres
	# launch postgres now
	launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

	# install ui query browser
	require_cask pgadmin3
fi

if [ "$NS_PLATFORM" == "linux" ]; then
	sudo apt-get install -y postgresql postgresql-contrib pgadmin3
fi

exit
