#!/usr/bin/env bash
# Usage: box luks
# Summary:
# Help: 
#
source "$_BOX_ROOT/lib/box_functions"
set -e



# # To add a new password, use luksAddKey:
# sudo cryptsetup luksAddKey /dev/sda5
#
# # To remove an existing password, use luksRemoveKey:
# sudo cryptsetup luksRemoveKey /dev/sda5

exit